baseURL = 'https://example.org/'
languageCode = 'en-us'
## languageCode = 'zh-CN'
title = '无聊的牛顿'
theme = "paper"


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'copuzzle'                 # github.com/YOUR_GITHUB_ID
  rss = true                                # show rss icon
  about = "/about"
  # home page profile
  # avatar = 'https://avatars.githubusercontent.com/u/2509640?v=4'                 # gravatar email or image url
  # name = 'Tsai Ming'
  bio = 'To be or not to be, that is the question.'

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  #gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  #graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  math = true                               # enable KaTeX math typesetting globally
  comments = true


# giscus
[params.giscus]
  repo = "copuzzle/copuzzle.github.io"                 # see https://giscus.app for more details
  repoId = 'MDEwOlJlcG9zaXRvcnk1OTgyNjE2NQ=='
  category = 'General'
  categoryId = 'DIC_kwDOA5Df9c4CbJZi'
  mapping = 'pathname'
  theme = 'light'
  lang = 'en'


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 10

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"